version: "3"

services:
  backend:
    container_name: backend_container
    build:
      context: ../backend
      dockerfile: ../backend/backend.dockerfile
#    restart: always
    ports:
      - "8080:8080"
#    deploy:
#      mode: replicated
#      replicas: 1
    env_file:
      - ./.env.prod
#    networks:
#      - backend

  frontend:
    container_name: frontend_container
    build:
      context: ../frontend
      dockerfile: ../frontend/frontend.dockerfile
#    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app
      - /app/node_modules
#    depends_on:
#      - backend
    env_file:
      - ./.env.prod
#    networks:
#      - frontend

#networks:
#  frontend:
#    driver: bridge
#  backend:
#    driver: bridge