version: "3.5"

services:
#  backend:
#    image: ebudaev/gonext_backend:v1
#    container_name: backend
#    restart: always
#    ports:
#      - "8000:8000"
#    deploy:
#      mode: replicated
#      replicas: 1
#    env_file:
#      - ./.env

  web:
    image: ebudaev/gonext_web:v1
    container_name: web
    restart: always
    env_file:
      - ./.env
#    volumes:
#      - /app
#      - /app/node_modules
#    depends_on:
#      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    depends_on:
      - web
#      - backend
