version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: ../backend/backend.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./.env.prod
    networks:
      - app-network

  web:
    container_name: web
    build:
      context: ../frontend
      dockerfile: ../frontend/frontend.dockerfile
    restart: always
    ports:
      - "3000:3000"
#    volumes:
#      - /app
#      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - ./.env.prod
    networks:
      - app-network

#  nginx:
#    image: nginx:1.19.3
#    ports:
#      - "8080:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    restart: always
#    depends_on:
#      - web
#      - backend
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge