version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: ../backend/backend.dockerfile
    restart: always
    ports:
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - app-network

  web:
    container_name: web
    build:
      context: ../frontend
      dockerfile: ../frontend/frontend.dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
